
# *Data Manipulation (numpy library) operations broadcasting indexing and slicing*

In [1]:
import numpy as np
import pandas as pd
#create a numpy array
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [13]:
b=5
result=arr1*b
print(result)

[ 5 10 15 20 25 30 35 40 45]


In [2]:
arr2 = np.array([10, 20, 30, 40, 50])

element = arr2[2]  # Accessing the third element
print(element)

30


In [3]:
subset = arr2[1:4]  # Extracting elements from index 1 to 3
print(subset)

[20 30 40]


In [4]:
# Slicing example
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_slice = matrix[1, :]  # Extracting the second row
print(row_slice)

[4 5 6]


In [5]:
column_slice = matrix[:, 1]  # Extracting the second column
print(column_slice)

[2 5 8]


In [6]:
submatrix = matrix[0:2, 1:]  # Extracting a submatrix from rows 1 and 2, and columns 2 and 3
print(submatrix)

[[2 3]
 [5 6]]


In [7]:
data = {'Name': ['Ankit', 'Bhavya', 'Charvi', 'Diya', 'Eesha'],

        'Age': [25, 30, 22, 28, 35],

        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}


In [8]:
df = pd.DataFrame(data)

In [9]:
#first element
df.head()

Name  Age      City
0   Ankit   25  New York
1  Bhavya   30    London
2  Charvi   22     Paris
3    Diya   28     Tokyo
4   Eesha   35    Sydney

In [10]:
#last elements
df.tail()

Name  Age      City
0   Ankit   25  New York
1  Bhavya   30    London
2  Charvi   22     Paris
3    Diya   28     Tokyo
4   Eesha   35    Sydney

In [11]:
#size of dataframe
len(df)

5

In [12]:
#remove null values
newdf = df.dropna()