In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Data Preprocessing
> Data preprocessing is a crucial step in preparing data for analysis or machine learning. It involves tasks like reading datasets, handling missing data, and converting data to a suitable format, often tensors, for efficient computation. Here's how you can approach these tasks:

### Reading the dataset
> Reading a dataset is the first step. The choice of library depends on the dataset format (CSV, Excel, etc.). The pandas library is commonly used for reading structured data.

In [2]:
import pandas as pd
import numpy as np

data=pd.read_csv('/content/drive/MyDrive/Deep Learning POE/ParisHousing.csv')
data.head(5)

squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0         75523              3        0        1      63      9373   
1         80771             39        1        1      98     39381   
2         55712             58        0        1      19     34457   
3         32316             47        0        0       6     27939   
4         70429             19        1        1      90     38045   

   cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector  \
0              3              8  2005           0                  1   
1              8              6  2015           1                  0   
2              6              8  2021           0                  0   
3             10              4  2012           0                  1   
4              3              7  1990           1                  0   

   basement  attic  garage  hasStorageRoom  hasGuestRoom      price  
0      4313   9005     956               0             7  7559081.5  
1      3653   2436     128               1             2  8085989.5  
2      2937   8852     135               1             9  5574642.1  
3       659   7141     359               0             3  3232561.2  
4      8435   2429     292               1             4  7055052.0

### Handling Null values / missing data
>Handling null (missing) values is a critical part of data preprocessing, as missing data can negatively impact the quality of analysis or machine learning models. The pandas library in Python provides various methods to handle null values effectively. Here's a detailed explanation of common null value handling techniques in pandas

In [3]:
# Detecting null values

print(data.isnull().sum()) #gives total null values per column

squareMeters         0
numberOfRooms        0
hasYard              0
hasPool              0
floors               0
cityCode             0
cityPartRange        0
numPrevOwners        0
made                 0
isNewBuilt           0
hasStormProtector    0
basement             0
attic                0
garage               0
hasStorageRoom       0
hasGuestRoom         0
price                0
dtype: int64


In [4]:
# Removing null values

df=data.dropna()  #deletes rows with null value
print(df.isnull().sum())

squareMeters         0
numberOfRooms        0
hasYard              0
hasPool              0
floors               0
cityCode             0
cityPartRange        0
numPrevOwners        0
made                 0
isNewBuilt           0
hasStormProtector    0
basement             0
attic                0
garage               0
hasStorageRoom       0
hasGuestRoom         0
price                0
dtype: int64


In [5]:
df=data.dropna(axis=1) # deletes columns with null values
print(df.isnull().sum())

squareMeters         0
numberOfRooms        0
hasYard              0
hasPool              0
floors               0
cityCode             0
cityPartRange        0
numPrevOwners        0
made                 0
isNewBuilt           0
hasStormProtector    0
basement             0
attic                0
garage               0
hasStorageRoom       0
hasGuestRoom         0
price                0
dtype: int64


In [6]:
# Creating a DataFrame with null values
data = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [6, np.nan, 8, np.nan, 10]
})
print(data)

     A     B
0  1.0   6.0
1  2.0   NaN
2  NaN   8.0
3  4.0   NaN
4  5.0  10.0


In [7]:
# Imputing Null values with mean
imputed_data=data.fillna(data.mean())
print(imputed_data)


     A     B
0  1.0   6.0
1  2.0   8.0
2  3.0   8.0
3  4.0   8.0
4  5.0  10.0


In [8]:
# Imputing Null values with specific value
imputed_data=data.fillna(0)
print(imputed_data)

     A     B
0  1.0   6.0
1  2.0   0.0
2  0.0   8.0
3  4.0   0.0
4  5.0  10.0


In [9]:

# Forward fill
data_ffill = data.fillna(method='ffill')
print(data_ffill)

     A     B
0  1.0   6.0
1  2.0   6.0
2  2.0   8.0
3  4.0   8.0
4  5.0  10.0


In [10]:

# Backward fill
data_bfill = data.fillna(method='bfill')
print(data_bfill)

     A     B
0  1.0   6.0
1  2.0   8.0
2  4.0   8.0
3  4.0  10.0
4  5.0  10.0


In [11]:
# Interpolation

data_interpolated = data.interpolate(method='linear')
print(data_interpolated)

     A     B
0  1.0   6.0
1  2.0   7.0
2  3.0   8.0
3  4.0   9.0
4  5.0  10.0


### Conversion to Tensor Format
> Tensors are fundamental data structures used for numerical computations, and they play a crucial role in various fields, particularly in machine learning and scientific computing. They are multi-dimensional arrays that can be used to represent data in a structured and efficient way. Here's a bit more detail about tensors and how they are used in different libraries

#### Numpy Tensors
>In the numpy library, tensors are implemented as numpy arrays. These arrays can have any number of dimensions and are used for various mathematical and numerical operations.

In [12]:
numpy_tensor=data_interpolated.to_numpy()
print(numpy_tensor)

[[ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]
 [ 5. 10.]]


#### PyTorch Tensors
>In the numpy library, tensors are implemented as numpy arrays. These arrays can have any number of dimensions and are used for various mathematical and numerical operations.

In [13]:
import torch

# Convert DataFrame to PyTorch tensor
torch_tensor = torch.tensor(data_interpolated.values)
print(torch_tensor)

tensor([[ 1.,  6.],
        [ 2.,  7.],
        [ 3.,  8.],
        [ 4.,  9.],
        [ 5., 10.]], dtype=torch.float64)


#### Tensorflow Tensors
>TensorFlow library also uses tensors as the primary data structure for building and training machine learning models.

In [14]:
import tensorflow as tf

# Convert DataFrame to TensorFlow tensor
tf_tensor = tf.constant(data_interpolated.values)
print(tf_tensor)

tf.Tensor(
[[ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]
 [ 5. 10.]], shape=(5, 2), dtype=float64)
